const APPLICATIONS := {
	"icon.svg": preload("res://icon.svg"),
	"icon.png": preload("res://addons/GodotTerminalButByTiffany/icon.png"),
	"plugin.gd": preload("res://addons/GodotTerminalButByTiffany/plugin.gd"),
	"smol.png": preload("res://addons/GodotTerminalButByTiffany/smol.png"),
	"terminal.gd": preload("res://addons/GodotTerminalButByTiffany/terminal.gd"),
	"terminal_application.gd": preload("res://addons/GodotTerminalButByTiffany/terminal_application.gd"),
	"terminal_menu.gd": preload("res://addons/GodotTerminalButByTiffany/terminal_menu.gd"),
	"terminal_menu.tscn": preload("res://addons/GodotTerminalButByTiffany/terminal_menu.tscn"),
	"Tiff-Terminal.png": preload("res://addons/GodotTerminalButByTiffany/Tiff-Terminal.png"),
	"clear.gd": preload("res://addons/GodotTerminalButByTiffany/applications/clear.gd"),
	"echo.gd": preload("res://addons/GodotTerminalButByTiffany/applications/echo.gd"),
	"func.gd": preload("res://addons/GodotTerminalButByTiffany/applications/func.gd"),
	"help.gd": preload("res://addons/GodotTerminalButByTiffany/applications/help.gd"),
	"quit.gd": preload("res://addons/GodotTerminalButByTiffany/applications/quit.gd"),
	"set.gd": preload("res://addons/GodotTerminalButByTiffany/applications/set.gd"),
	"spawn.gd": preload("res://addons/GodotTerminalButByTiffany/applications/spawn.gd"),
	"test.gd": preload("res://addons/GodotTerminalButByTiffany/applications/test.gd"),
	"tree.gd": preload("res://addons/GodotTerminalButByTiffany/applications/tree.gd"),
	"generate_terminal_registry.gd": preload("res://addons/GodotTerminalButByTiffany/editor_tools/generate_terminal_registry.gd"),
	"windows_command_prompt.ttf": preload("res://addons/GodotTerminalButByTiffany/Font/windows_command_prompt.ttf"),
	"app_registry.gd": preload("res://addons/GodotTerminalButByTiffany/registries/app_registry.gd"),
	"file_registry.gd": preload("res://addons/GodotTerminalButByTiffany/registries/file_registry.gd"),
	"font_registry.gd": preload("res://addons/GodotTerminalButByTiffany/registries/font_registry.gd"),
}
